### 0.0 health check
// @no-log
GET {{host_url}}/health
Authorization: Bearer {{access_token}}

### 1.0 임시 회원가입
// @no-log
POST {{host_url}}/sign-up
Content-Type: application/json

{
  "email": "{{user.API_1_0_SIGNUP.email}}",
  "password": "{{user.API_1_0_SIGNUP.password}}",
  "name": "{{user.API_1_0_SIGNUP.name}}",
  "nickname": "{{user.API_1_0_SIGNUP.nickname}}",
  "birth": "{{user.API_1_0_SIGNUP.birth}}"
}


### 1.1 로그인
// @no-log
POST {{host_url}}/sign-in
Content-Type: application/json

{
  "email": "{{user.API_1_1_SIGNIN.email}}",
  "password": "{{user.API_1_1_SIGNIN.password}}"
}

> {%
    client.global.set("access_token", response.body.result.access_token);
%}


### 1.2 인증코드 인증
// @no-log
POST {{host_url}}/validation/authentication-code
Content-Type: application/json

{
  "email": "{{user.API_1_2_AUTHENTICATION_CODE.email}}",
  "authentication_code": "{{user.API_1_2_AUTHENTICATION_CODE.authentication_code}}"
}

### 1.3 유저 룸 정보 조회
GET {{host_url}}/room/profile?userId=595da97f-64b2-4851-8fe0-e99ec3af6015

### 2,0 채널 생성
// @no-log
POST {{host_url}}/room/create
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "room_id": "{{signaling.API_2_0_CREATE_CHAT_ROOM.chat_room_id}}"
}

### 2.1 채널 참여
// @no-log
POST {{host_url}}/room/{{signaling.API_2_0_CREATE_CHAT_ROOM.chat_room_id}}/join
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 2.2 채널 참여 중인 유저 조회
// @no-log
GET {{host_url}}/room/{{signaling.API_2_0_CREATE_CHAT_ROOM.chat_room_id}}/users
Authorization: Bearer {{access_token}}